### ISSUE TITLE
"Liturgy of any day" page is off by 1 day

### ISSUE THREAD

**Issue by hudon** [Liturgical-Calendar/LiturgicalCalendarFrontend#59] opened 2022-04-15 20:36 UTC
On the "Liturgy of any day" page, entering in a Day returns results for the day preceding the input day, see screenshot:

<img width="590" alt="Screen Shot 2022-04-15 at 13 35 23" src="https://user-images.githubusercontent.com/407222/163629632-7c2458f8-799c-45e7-8955-cb624d5dbf80.png">

code (but the bug may be in the backend):
https://github.com/Liturgical-Calendar/LiturgicalCalendarFrontend/blob/main/liturgyOfAnyDay.php#L81

**Comment by JohnRDOrazio** [comment] 2022-04-18 11:00
I'll try to investigate this further. It seems to me that it was working alright, but maybe daylight savings has had an effect.

I'm also seeing that the calendar for Italy is currently not working for that example, I'll have to look into that.

I have tried to use UTC timestamps consistently throughout the backend, to avoid timezone issues. On the frontend javascript is generally tainted with a timezone, so it probably has something to do with making sure a UTC value is sent to the backend in the initial request, otherwise translating between javascript timestamps and PHP UTC timestamps can easily wind up with day off values.

**Comment by JohnRDOrazio** [comment] 2022-04-18 12:32
Italian calendar is working again, I just needed to do a `git pull` in the `api/v3` directory to pull in the latest updates from the development branch.

**Comment by hudon** [comment] 2022-04-18 17:37
<img width="623" alt="Screen Shot 2022-04-18 at 10 36 35" src="https://user-images.githubusercontent.com/407222/163848993-b1e424f9-99a0-49cf-93b9-b6db5d2cd10f.png">

same issue. I open the page and it says 18 in the input form but 17 in the output. It's reproducible on latest Safari and Edge, macOS 12.4.

**Comment by JohnRDOrazio** [comment] 2022-04-18 17:58
Problem can't be on the backend, because the backend only sends data for an entire year. There is no backend communication for a single day, requests are sent to the backend only if the year changes or if the calendar changes. Must have to do with how javascript dates are being handled.

In the PHP backend, all dates are handled as UTC, and the timestamp associated with any given liturgical "event" is therefore in UTC.

In the frontend, the request for a single day is processed by simply filtering through all possible liturgical events for those that have the same UTC timestamp as the day requested:

https://github.com/Liturgical-Calendar/LiturgicalCalendarFrontend/blob/ec240c11623a1986d94784b3c5b1f2e219ef8dc4/assets/js/liturgyOfAnyDay.js#L93-L97

https://github.com/Liturgical-Calendar/LiturgicalCalendarFrontend/blob/ec240c11623a1986d94784b3c5b1f2e219ef8dc4/assets/js/liturgyOfAnyDay.js#L130-L131

**Comment by hudon** [comment] 2022-04-18 18:06
```
 newDate = new Date(Date.UTC(year, month - 1, day, 0, 0, 0)); 
 let timestamp = newDate.getTime() / 1000; 
```
Is this redundant? I think you can do `let timestamp = Date.UTC(year, month - 1, day, 0, 0, 0) / 1000` and thus not introduce a `Date` object

**Comment by JohnRDOrazio** [comment] 2022-04-18 18:07
Looking at the example you posted, I see the liturgical event that is returned is correct:

**Nativity of Saint John the Baptist** is in fact on June 23rd as requested.

The string at the top of the box that is supposed to show the date requested in a localized form, is showing **June 22nd** even though **June 23rd** was requested, and results for **June 23rd** are being shown. So it has to do with the localization of the date:

https://github.com/Liturgical-Calendar/LiturgicalCalendarFrontend/blob/ec240c11623a1986d94784b3c5b1f2e219ef8dc4/assets/js/liturgyOfAnyDay.js#L192

**Comment by hudon** [comment] 2022-04-18 18:08
Oh I see. Yea it should be localized _format_ without localizing the date/time

**Comment by JohnRDOrazio** [comment] 2022-04-18 18:14
I think this commit might fix the issue: a30723b0f37f9256dc8f1cd2bd34513838e8b883

Can you test again on the staging page and see if it's fixed?

**Comment by hudon** [comment] 2022-04-18 19:48
<img width="602" alt="Screen Shot 2022-04-18 at 12 48 28" src="https://user-images.githubusercontent.com/407222/163867519-98654e56-d99a-40fd-a048-54599c0363bf.png">

same thing. Can you repro?

**Comment by JohnRDOrazio** [comment] 2022-04-18 20:01
Probably being so close to UTC time here in Rome, it's not easy to reproduce. I'll have to try changing my system time, or try somewhere near midnight.Il 18 Apr 2022 21:48, James Hudon ***@***.***> ha scritto:

same thing. Can you repro?

**Comment by JohnRDOrazio** [comment] 2022-04-18 21:18
I tried setting my system clock to all different timezones, and I am able to reproduce on https://litcal.johnromanodorazio.com/liturgyOfAnyDay.php, I am not able to reproduce instead on https://litcal-staging.johnromanodorazio.com/liturgyOfAnyDay.php after the last commit. Can you please verify that you are testing against https://litcal-staging.johnromanodorazio.com/liturgyOfAnyDay.php and not https://litcal.johnromanodorazio.com/liturgyOfAnyDay.php ?

**Comment by hudon** [comment] 2022-04-18 21:20
Verified:

<img width="752" alt="Screen Shot 2022-04-18 at 14 19 48" src="https://user-images.githubusercontent.com/407222/163879834-cd77f542-09f5-4a9a-a9f2-c1b47078364f.png">

**Comment by hudon** [comment] 2022-04-18 21:21
I'm in Pacific Daylight Time (PDT), if it helps.

**Comment by JohnRDOrazio** [comment] 2022-04-18 21:27
can you make sure you have force refreshed the page / emptied the cache? Since it's a fix on the javascript side, if the javascript is still cached it won't show as fixed... In Chrome the only surefire way I have of doing this (and Edge is chromium based now), is by opening developer tool settings and checking **Disable cache (while Dev Tools is open)**, then refreshing the page. Sometimes <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> will do the trick, but if not I use the dev tools checkbox, and keep it open while I force refresh the page. Either that, or open an Incognito window...

**Comment by hudon** [comment] 2022-04-18 21:29
yup, JS was cached. Looks good now 👍🏻

**Comment by JohnRDOrazio** [comment] 2022-04-18 21:31
Fixed in commit https://github.com/Liturgical-Calendar/LiturgicalCalendarFrontend/commit/a30723b0f37f9256dc8f1cd2bd34513838e8b883

**Closed by JohnRDOrazio** 2022-04-18 21:31 UTC
Labels: bug
